require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  response = RestClient.get "https://www.dnd5eapi.co/api/spells/acid-arrow"
  spell_hash = JSON.parse(response)
  spell_hash["name"]
  spell_hash.keys
  # Open a Pry session
  Pry.start
end
